### ISSUE TITLE
App instantly crashes and does not start

### ISSUE THREAD

**Issue by ITCMD** [gatekeep/MDCTool#2]
On Windows 11, using the beta download in "releases," the app does not open.

The task is not present in task manager.

**Comment by GrayMatter** [comment]
App Crash due to an unhandled exception.
Exception Info: NAudio.MmException
   at NAudio.Wave.WaveIn.OpenWaveInDevice()
   at NAudio.Wave.WaveIn.StartRecording()
   at MDCTool.MainWindow.InitializeInputAudio()
   at MDCTool.MainWindow..ctor()
   at MDCTool.EntryPoint.Main()

Sounds like Windows 11 does not like the way it is trying to access audio input or could be a driver conflict.  I haven't downloaded the source code yet to test.

**Comment by ITCMD** [comment]
I downloaded the source code but cannot figure out how to compile it :D

**Comment by GrayMatter** [comment]
to build from source, you need visual studio and NAudio library dependency at a minimum.  It may be all you need is a compiled NAudio dll but there may be additional dependencies I haven't seen yet.

**Comment by GrayMatter** [comment]
That worked.  I updated my NAudio library to the latest 2.2.1 and it compiled correctly.

**Comment by GrayMatter** [comment]
I submitted a pull request but have also put the binaries on my fork for now. @ITCMD

**Comment by ITCMD** [comment]
Awesome, thanks!

**Comment by gatekeep** [comment]
Closed with PR#3.
